// action - customization reducer
export const SET_MENU = '@customization/SET_MENU';
export const MENU_TOGGLE = '@customization/MENU_TOGGLE';
export const MENU_OPEN = '@customization/MENU_OPEN';
export const SET_FONT_FAMILY = '@customization/SET_FONT_FAMILY';
export const SET_BORDER_RADIUS = '@customization/SET_BORDER_RADIUS';
export const CHECK_LOGIN = '@customization/CHECK_LOGIN';
export const DATA_USER = '@customization/DATA_USER';
export const CART = '@customization/CART';
export const ADD_TO_CART = '@customization/ADD_TO_CART';
export const  UPDATE_CART_ITEM = '@customization/UPDATE_CART_ITEM';
export const REMOVE_ITEM_CART = '@customization/REMOVE_ITEM_CART';
